### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by wangrq4** [oxff644/WBread#2]
您好，我是一名大四的学生，我想学习一下您的这个项目，希望得到您的回复

**Comment by oxff644** [comment]
您好，可以先看下这篇文章：https://mp.weixin.qq.com/s/l4NKlRrqEzqWz6MAfZTxkA 如果还有疑问可以私信我～

**Comment by oxff644** [comment]
> 



> 您好，我是一名大四的学生，我想学习一下您的这个项目，希望得到您的回复

您好，可以先看下这篇文章：https://mp.weixin.qq.com/s/l4NKlRrqEzqWz6MAfZTxkA 如果还有疑问可以私信我～

**Comment by oxff644** [comment]
> > 
> 
> > 您好，我是一名大四的学生，我想学习一下您的这个项目，希望得到您的回复
> 
> 您好，可以先看下这篇文章：https://mp.weixin.qq.com/s/l4NKlRrqEzqWz6MAfZTxkA 如果还有疑问可以私信我～

issue 我先关了唷，有疑问可以重开哈
