### ISSUE TITLE
AttributeError: module 'ipdb' has no attribute 'District'

### ISSUE THREAD

**Issue by SkinAir** [oxff644/WBread#3]
好像是main.py第39行ipipfree.ipdb，跟import ipdb冲突了

**Comment by s045pd** [comment]
> 好像是main.py第39行ipipfree.ipdb，跟import ipdb冲突了

@SkinAir  这边的ipdb使用的是项目：https://github.com/ipipdotnet/ipdb-python
所以可以删除原有ipdb并安装下如下依赖 : )
```python
pip install ipip-ipdb
```

**Comment by SkinAir** [comment]
> > 好像是 main.py 第39行ipfree.ipdb，跟import ipdb冲突了
> 
> @SkinAir 这边的ipdb使用的是项目：https://github.com/ipipdotnet/ipdb-python 所以可以删除原有ipdb并安装下如下依赖 ： ）
> 
> ```python
> pip install ipip-ipdb
> ```

谢谢，问题解决
